pipeline {
    agent any

    stages {
        stage('代码拉取') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/taxi_service']], extensions: [], userRemoteConfigs: [[credentialsId: 'f98411a7-74b5-4f6f-a32a-7ec84ffa116d', url: 'git@github.com:Sherlock-White/2021-sse-soa-project.git']]])
            }
        }
        stage('编译、构建、打包、部署') {
            steps {
                dir('./BackEnd/taxi_service') {
                    sh 'mvn clean package dockerfile:build'
                }


            }
        }
    }
}
